const searchResults =
    [ { name: 'Lionel Messi',
    nationality: 'Argentina',
    club: 'Barcelona',
    URL:
        'https://www.whoscored.com/Players/11119/History/Lionel-Messi' },
    { name: 'Mbida Messi',
        nationality: 'Cameroon',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/70719/History/Mbida-Messi' },
    { name: 'Messi Essomba',
        nationality: 'Cameroon',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/331370/History/Messi-Essomba' },
    { name: 'Enguene Junior Messi',
        nationality: 'Cameroon',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/309702/History/Enguene-Junior-Messi' } ];

const stats =
    { '2019/2020 - UCL|Barcelona':
        { minutes: 211,
            assists: 1,
            goals: 1,
            succPasses: 113,
            totalPasses: 134,
            succLongPasses: 6,
            totalLongPasses: 8,
            shots: 10,
            penaltiesTaken: 0,
            keyPasses: 10,
            shotsOnTarget: 6,
            fouls: 1,
            tackles: 0,
            dribbledPast: 3,
            interceptions: 3,
            possessionLosses: 3,
            dribbles: 22,
            clearances: 0,
            totalAerialDuels: 1,
            succAerialDuels: 0,
            succCrosses: 1,
            totalCrosses: 9,
            blocks: 0,
            throughBalls: 3 },
    '2019/2020 - SLL|Barcelona':
        { minutes: 271,
            assists: 2,
            goals: 2,
            succPasses: 116,
            totalPasses: 153,
            succLongPasses: 6,
            totalLongPasses: 13,
            shots: 12,
            penaltiesTaken: 0,
            keyPasses: 7,
            shotsOnTarget: 5,
            fouls: 0,
            tackles: 3,
            dribbledPast: 2,
            interceptions: 0,
            possessionLosses: 6,
            dribbles: 19,
            clearances: 0,
            totalAerialDuels: 3,
            succAerialDuels: 2,
            succCrosses: 1,
            totalCrosses: 6,
            blocks: 0,
            throughBalls: 0 },
    '2019 - ICA|Argentina':
        { minutes: 487,
            assists: 1,
            goals: 0,
            succPasses: 170,
            totalPasses: 210,
            succLongPasses: 3,
            totalLongPasses: 4,
            shots: 17,
            penaltiesTaken: 1,
            keyPasses: 11,
            shotsOnTarget: 7,
            fouls: 5,
            tackles: 6,
            dribbledPast: 7,
            interceptions: 2,
            possessionLosses: 11,
            dribbles: 22,
            clearances: 0,
            totalAerialDuels: 3,
            succAerialDuels: 0,
            succCrosses: 2,
            totalCrosses: 16,
            blocks: 0,
            throughBalls: 4.199999999999999 },
    '2018/2019 - UCL|Barcelona':
        { minutes: 837,
            assists: 3,
            goals: 11,
            succPasses: 501,
            totalPasses: 593,
            succLongPasses: 34,
            totalLongPasses: 43,
            shots: 54,
            penaltiesTaken: 1,
            keyPasses: 27,
            shotsOnTarget: 26,
            fouls: 8,
            tackles: 10,
            dribbledPast: 4,
            interceptions: 3,
            possessionLosses: 23,
            dribbles: 35,
            clearances: 0,
            totalAerialDuels: 4,
            succAerialDuels: 1,
            succCrosses: 3,
            totalCrosses: 13,
            blocks: 0,
            throughBalls: 9 },
    '2018/2019 - SLL|Barcelona':
        { minutes: 2710,
            assists: 13,
            goals: 32,
            succPasses: 1487,
            totalPasses: 1830,
            succLongPasses: 115,
            totalLongPasses: 154,
            shots: 170,
            penaltiesTaken: 5,
            keyPasses: 92,
            shotsOnTarget: 87,
            fouls: 22,
            tackles: 12,
            dribbledPast: 16,
            interceptions: 3,
            possessionLosses: 78,
            dribbles: 134,
            clearances: 0,
            totalAerialDuels: 17,
            succAerialDuels: 7,
            succCrosses: 14,
            totalCrosses: 78,
            blocks: 0,
            throughBalls: 30.6 },
    '2018 - WC|Argentina':
        { minutes: 360,
            assists: 2,
            goals: 1,
            succPasses: 168,
            totalPasses: 205,
            succLongPasses: 4,
            totalLongPasses: 9,
            shots: 18,
            penaltiesTaken: 1,
            keyPasses: 10,
            shotsOnTarget: 6,
            fouls: 4,
            tackles: 5,
            dribbledPast: 6,
            interceptions: 1,
            possessionLosses: 16,
            dribbles: 23,
            clearances: 0,
            totalAerialDuels: 5,
            succAerialDuels: 0,
            succCrosses: 2,
            totalCrosses: 8,
            blocks: 0,
            throughBalls: 1.2 },
    '2017/2018 - UCL|Barcelona':
        { minutes: 783,
            assists: 2,
            goals: 6,
            succPasses: 402,
            totalPasses: 493,
            succLongPasses: 15,
            totalLongPasses: 23,
            shots: 44,
            penaltiesTaken: 0,
            keyPasses: 17,
            shotsOnTarget: 24,
            fouls: 3,
            tackles: 9,
            dribbledPast: 7,
            interceptions: 3,
            possessionLosses: 31,
            dribbles: 37,
            clearances: 0,
            totalAerialDuels: 4,
            succAerialDuels: 2,
            succCrosses: 2,
            totalCrosses: 24,
            blocks: 0,
            throughBalls: 3 },
    '2017/2018 - SLL|Barcelona':
        { minutes: 2997,
            assists: 12,
            goals: 32,
            succPasses: 1529,
            totalPasses: 1883,
            succLongPasses: 75,
            totalLongPasses: 111,
            shots: 197,
            penaltiesTaken: 4,
            keyPasses: 87,
            shotsOnTarget: 96,
            fouls: 17,
            tackles: 17,
            dribbledPast: 16,
            interceptions: 7,
            possessionLosses: 107,
            dribbles: 185,
            clearances: 0,
            totalAerialDuels: 19,
            succAerialDuels: 8,
            succCrosses: 11,
            totalCrosses: 52,
            blocks: 1,
            throughBalls: 18 },
    '2016/2017 - UCL|Barcelona':
        { minutes: 810,
            assists: 2,
            goals: 9,
            succPasses: 395,
            totalPasses: 485,
            succLongPasses: 27,
            totalLongPasses: 40,
            shots: 38,
            penaltiesTaken: 2,
            keyPasses: 19,
            shotsOnTarget: 16,
            fouls: 5,
            tackles: 10,
            dribbledPast: 9,
            interceptions: 0,
            possessionLosses: 23,
            dribbles: 28,
            clearances: 0,
            totalAerialDuels: 10,
            succAerialDuels: 1,
            succCrosses: 5,
            totalCrosses: 25,
            blocks: 1,
            throughBalls: 3.6 },
    '2016/2017 - SLL|Barcelona':
        { minutes: 2833,
            assists: 9,
            goals: 31,
            succPasses: 1320,
            totalPasses: 1646,
            succLongPasses: 92,
            totalLongPasses: 135,
            shots: 179,
            penaltiesTaken: 7,
            keyPasses: 79,
            shotsOnTarget: 77,
            fouls: 14,
            tackles: 23,
            dribbledPast: 13,
            interceptions: 7,
            possessionLosses: 90,
            dribbles: 126,
            clearances: 1,
            totalAerialDuels: 19,
            succAerialDuels: 6,
            succCrosses: 11,
            totalCrosses: 43,
            blocks: 0,
            throughBalls: 20.4 },
    '2015/2016 - UCL|Barcelona':
        { minutes: 630,
            assists: 1,
            goals: 5,
            succPasses: 408,
            totalPasses: 479,
            succLongPasses: 17,
            totalLongPasses: 29,
            shots: 39,
            penaltiesTaken: 1,
            keyPasses: 10,
            shotsOnTarget: 14,
            fouls: 2,
            tackles: 5,
            dribbledPast: 5,
            interceptions: 1,
            possessionLosses: 19,
            dribbles: 34,
            clearances: 0,
            totalAerialDuels: 8,
            succAerialDuels: 3,
            succCrosses: 2,
            totalCrosses: 9,
            blocks: 0,
            throughBalls: 0.7000000000000001 },
    '2015/2016 - SLL|Barcelona':
        { minutes: 2730,
            assists: 16,
            goals: 23,
            succPasses: 1505,
            totalPasses: 1838,
            succLongPasses: 117,
            totalLongPasses: 162,
            shots: 158,
            penaltiesTaken: 7,
            keyPasses: 77,
            shotsOnTarget: 75,
            fouls: 13,
            tackles: 11,
            dribbledPast: 7,
            interceptions: 6,
            possessionLosses: 74,
            dribbles: 117,
            clearances: 0,
            totalAerialDuels: 14,
            succAerialDuels: 5,
            succCrosses: 14,
            totalCrosses: 48,
            blocks: 0,
            throughBalls: 33 },
    '2015 - ICA|Argentina':
        { minutes: 602,
            assists: 3,
            goals: 0,
            succPasses: 261,
            totalPasses: 310,
            succLongPasses: 11,
            totalLongPasses: 18,
            shots: 27,
            penaltiesTaken: 1,
            keyPasses: 14,
            shotsOnTarget: 8,
            fouls: 3,
            tackles: 6,
            dribbledPast: 3,
            interceptions: 1,
            possessionLosses: 20,
            dribbles: 42,
            clearances: 0,
            totalAerialDuels: 7,
            succAerialDuels: 3,
            succCrosses: 5,
            totalCrosses: 13,
            blocks: 0,
            throughBalls: 1.7999999999999998 },
    '2014/2015 - UCL|Barcelona':
        { minutes: 1146,
            assists: 5,
            goals: 10,
            succPasses: 722,
            totalPasses: 838,
            succLongPasses: 28,
            totalLongPasses: 37,
            shots: 56,
            penaltiesTaken: 1,
            keyPasses: 36,
            shotsOnTarget: 26,
            fouls: 10,
            tackles: 14,
            dribbledPast: 14,
            interceptions: 7,
            possessionLosses: 27,
            dribbles: 92,
            clearances: 0,
            totalAerialDuels: 17,
            succAerialDuels: 10,
            succCrosses: 2,
            totalCrosses: 24,
            blocks: 0,
            throughBalls: 14.3 },
    '2014/2015 - SLL|Barcelona':
        { minutes: 3375,
            assists: 18,
            goals: 38,
            succPasses: 1934,
            totalPasses: 2334,
            succLongPasses: 104,
            totalLongPasses: 148,
            shots: 187,
            penaltiesTaken: 6,
            keyPasses: 95,
            shotsOnTarget: 94,
            fouls: 25,
            tackles: 27,
            dribbledPast: 12,
            interceptions: 7,
            possessionLosses: 76,
            dribbles: 174,
            clearances: 1,
            totalAerialDuels: 31,
            succAerialDuels: 9,
            succCrosses: 18,
            totalCrosses: 80,
            blocks: 1,
            throughBalls: 34.2 },
    '2014 - WC|Argentina':
        { minutes: 694,
            assists: 1,
            goals: 4,
            succPasses: 214,
            totalPasses: 267,
            succLongPasses: 12,
            totalLongPasses: 16,
            shots: 21,
            penaltiesTaken: 0,
            keyPasses: 21,
            shotsOnTarget: 8,
            fouls: 6,
            tackles: 10,
            dribbledPast: 3,
            interceptions: 1,
            possessionLosses: 21,
            dribbles: 39,
            clearances: 0,
            totalAerialDuels: 3,
            succAerialDuels: 0,
            succCrosses: 8,
            totalCrosses: 26,
            blocks: 0,
            throughBalls: 4.2 },
    '2013/2014 - UCL|Barcelona':
        { minutes: 630,
            assists: 0,
            goals: 6,
            succPasses: 358,
            totalPasses: 417,
            succLongPasses: 6,
            totalLongPasses: 8,
            shots: 33,
            penaltiesTaken: 2,
            keyPasses: 16,
            shotsOnTarget: 12,
            fouls: 0,
            tackles: 3,
            dribbledPast: 5,
            interceptions: 4,
            possessionLosses: 16,
            dribbles: 25,
            clearances: 0,
            totalAerialDuels: 4,
            succAerialDuels: 2,
            succCrosses: 1,
            totalCrosses: 12,
            blocks: 0,
            throughBalls: 7 },
    '2013/2014 - SLL|Barcelona':
        { minutes: 2508,
            assists: 11,
            goals: 21,
            succPasses: 1167,
            totalPasses: 1375,
            succLongPasses: 34,
            totalLongPasses: 44,
            shots: 155,
            penaltiesTaken: 7,
            keyPasses: 73,
            shotsOnTarget: 69,
            fouls: 11,
            tackles: 14,
            dribbledPast: 5,
            interceptions: 2,
            possessionLosses: 67,
            dribbles: 142,
            clearances: 0,
            totalAerialDuels: 23,
            succAerialDuels: 5,
            succCrosses: 10,
            totalCrosses: 60,
            blocks: 0,
            throughBalls: 12.4 },
    '2012/2013 - UCL|Barcelona':
        { minutes: 827,
            assists: 2,
            goals: 8,
            succPasses: 572,
            totalPasses: 656,
            succLongPasses: 22,
            totalLongPasses: 24,
            shots: 41,
            penaltiesTaken: 0,
            keyPasses: 17,
            shotsOnTarget: 20,
            fouls: 1,
            tackles: 2,
            dribbledPast: 3,
            interceptions: 6,
            possessionLosses: 33,
            dribbles: 21,
            clearances: 0,
            totalAerialDuels: 7,
            succAerialDuels: 3,
            succCrosses: 4,
            totalCrosses: 20,
            blocks: 0,
            throughBalls: 5.5 },
    '2012/2013 - SLL|Barcelona':
        { minutes: 2644,
            assists: 12,
            goals: 42,
            succPasses: 1499,
            totalPasses: 1760,
            succLongPasses: 67,
            totalLongPasses: 81,
            shots: 163,
            penaltiesTaken: 4,
            keyPasses: 46,
            shotsOnTarget: 80,
            fouls: 12,
            tackles: 20,
            dribbledPast: 10,
            interceptions: 9,
            possessionLosses: 82,
            dribbles: 122,
            clearances: 1,
            totalAerialDuels: 20,
            succAerialDuels: 5,
            succCrosses: 5,
            totalCrosses: 41,
            blocks: 1,
            throughBalls: 12.8 },
    '2011/2012 - UCL|Barcelona':
        { minutes: 990,
            assists: 5,
            goals: 10,
            succPasses: 773,
            totalPasses: 890,
            succLongPasses: 17,
            totalLongPasses: 21,
            shots: 76,
            penaltiesTaken: 5,
            keyPasses: 32,
            shotsOnTarget: 35,
            fouls: 13,
            tackles: 7,
            dribbledPast: 1,
            interceptions: 3,
            possessionLosses: 40,
            dribbles: 44,
            clearances: 0,
            totalAerialDuels: 2,
            succAerialDuels: 1,
            succCrosses: 3,
            totalCrosses: 23,
            blocks: 0,
            throughBalls: 15.399999999999999 },
    '2011/2012 - SLL|Barcelona':
        { minutes: 3268,
            assists: 16,
            goals: 40,
            succPasses: 1988,
            totalPasses: 2360,
            succLongPasses: 52,
            totalLongPasses: 68,
            shots: 202,
            penaltiesTaken: 11,
            keyPasses: 92,
            shotsOnTarget: 100,
            fouls: 27,
            tackles: 23,
            dribbledPast: 12,
            interceptions: 23,
            possessionLosses: 96,
            dribbles: 176,
            clearances: 2,
            totalAerialDuels: 12,
            succAerialDuels: 3,
            succCrosses: 16,
            totalCrosses: 89,
            blocks: 1,
            throughBalls: 55.5 },
    '2010/2011 - UCL|Barcelona':
        { minutes: 1048,
            assists: 3,
            goals: 11,
            succPasses: 793,
            totalPasses: 895,
            succLongPasses: 9,
            totalLongPasses: 11,
            shots: 69,
            penaltiesTaken: 2,
            keyPasses: 24,
            shotsOnTarget: 35,
            fouls: 17,
            tackles: 9,
            dribbledPast: 6,
            interceptions: 9,
            possessionLosses: 42,
            dribbles: 79,
            clearances: 0,
            totalAerialDuels: 6,
            succAerialDuels: 1,
            succCrosses: 3,
            totalCrosses: 8,
            blocks: 2,
            throughBalls: 11.700000000000001 },
    '2010/2011 - SLL|Barcelona':
        { minutes: 2859,
            assists: 18,
            goals: 27,
            succPasses: 1924,
            totalPasses: 2233,
            succLongPasses: 47,
            totalLongPasses: 56,
            shots: 150,
            penaltiesTaken: 4,
            keyPasses: 67,
            shotsOnTarget: 80,
            fouls: 22,
            tackles: 23,
            dribbledPast: 12,
            interceptions: 21,
            possessionLosses: 95,
            dribbles: 186,
            clearances: 0,
            totalAerialDuels: 14,
            succAerialDuels: 4,
            succCrosses: 8,
            totalCrosses: 47,
            blocks: 1,
            throughBalls: 33 },
    '2009/2010 - UCL|Barcelona':
        { minutes: 897,
            assists: 0,
            goals: 8,
            succPasses: 489,
            totalPasses: 565,
            succLongPasses: 15,
            totalLongPasses: 19,
            shots: 49,
            penaltiesTaken: 0,
            keyPasses: 19,
            shotsOnTarget: 27,
            fouls: 10,
            tackles: 6,
            dribbledPast: 5,
            interceptions: 10,
            possessionLosses: 29,
            dribbles: 57,
            clearances: 0,
            totalAerialDuels: 5,
            succAerialDuels: 2,
            succCrosses: 2,
            totalCrosses: 17,
            blocks: 0,
            throughBalls: 9 },
    '2009/2010 - SLL|Barcelona':
        { minutes: 2841,
            assists: 10,
            goals: 33,
            succPasses: 1328,
            totalPasses: 1549,
            succLongPasses: 47,
            totalLongPasses: 56,
            shots: 163,
            penaltiesTaken: 1,
            keyPasses: 65,
            shotsOnTarget: 86,
            fouls: 29,
            tackles: 31,
            dribbledPast: 17,
            interceptions: 41,
            possessionLosses: 89,
            dribbles: 145,
            clearances: 0,
            totalAerialDuels: 18,
            succAerialDuels: 7,
            succCrosses: 22,
            totalCrosses: 62,
            blocks: 0,
            throughBalls: 24.5 } };


module.exports = {
    searchResults, stats
};