const searchResults = [ { name: 'Ronaldo',
    nationality: 'Brazil',
    club: 'N/A',
    URL: 'https://www.whoscored.com/Players/51093/History/Ronaldo' },
    { name: 'Ronaldo',
        nationality: 'Brazil',
        club: 'Calcio Padova',
        URL: 'https://www.whoscored.com/Players/79508/History/Ronaldo' },
    { name: 'Ronaldo',
        nationality: 'Brazil',
        club: 'N/A',
        URL: 'https://www.whoscored.com/Players/102062/History/Ronaldo' },
    { name: 'Ronaldo',
        nationality: 'Brazil',
        club: 'N/A',
        URL: 'https://www.whoscored.com/Players/129537/History/Ronaldo' },
    { name: 'Ronaldo',
        nationality: 'Brazil',
        club: 'N/A',
        URL: 'https://www.whoscored.com/Players/148581/History/Ronaldo' },
    { name: 'Ronaldo',
        nationality: 'Brazil',
        club: 'Bahia',
        URL: 'https://www.whoscored.com/Players/299394/History/Ronaldo' },
    { name: 'Ronaldo',
        nationality: 'Brazil',
        club: 'N/A',
        URL: 'https://www.whoscored.com/Players/330555/History/Ronaldo' },
    { name: 'Cristiano Ronaldo',
        nationality: 'Portugal',
        club: 'Juventus',
        URL:
            'https://www.whoscored.com/Players/5583/History/Cristiano-Ronaldo' },
    { name: 'Ronaldo Vanin',
        nationality: 'Brazil',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/20417/History/Ronaldo-Vanin' },
    { name: 'Ronaldo Loaiza',
        nationality: 'Guatemala',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/24479/History/Ronaldo-Loaiza' },
    { name: 'Tiago Ronaldo',
        nationality: 'Portugal',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/34104/History/Tiago-Ronaldo' },
    { name: 'Marczinski Ronaldo',
        nationality: 'Brazil',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/43989/History/Marczinski-Ronaldo' },
    { name: 'Ronaldo Alves',
        nationality: 'Brazil',
        club: 'CS Alagoano',
        URL:
            'https://www.whoscored.com/Players/78210/History/Ronaldo-Alves' },
    { name: 'Ronaldo Tres',
        nationality: 'Brazil',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/92033/History/Ronaldo-Tres' },
    { name: 'Ronaldo Guiaro',
        nationality: 'Brazil',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/129710/History/Ronaldo-Guiaro' },
    { name: 'Ronaldo Johnson',
        nationality: 'Ecuador',
        club: 'Emelec',
        URL:
            'https://www.whoscored.com/Players/143857/History/Ronaldo-Johnson' },
    { name: 'Ronaldo Tipian',
        nationality: 'Venezuela',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/145437/History/Ronaldo-Tipian' },
    { name: 'Ronaldo Mendes',
        nationality: 'Brazil',
        club: 'Al-Wasl',
        URL:
            'https://www.whoscored.com/Players/229197/History/Ronaldo-Mendes' },
    { name: 'Ronaldo Cisneros',
        nationality: 'Mexico',
        club: 'CD Guadalajara',
        URL:
            'https://www.whoscored.com/Players/236004/History/Ronaldo-Cisneros' },
    { name: 'Ronaldo Perez',
        nationality: 'Venezuela',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/242798/History/Ronaldo-Perez' },
    { name: 'Ronaldo Barbosa',
        nationality: 'Brazil',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/276453/History/Ronaldo-Barbosa' },
    { name: 'Ronaldo Martinez',
        nationality: 'Paraguay',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/286127/History/Ronaldo-Martinez' },
    { name: 'Ronaldo Rodney',
        nationality: 'Jamaica',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/287323/History/Ronaldo-Rodney' },
    { name: 'Ronaldo Tavares',
        nationality: 'Portugal',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/302327/History/Ronaldo-Tavares' },
    { name: 'Ronaldo Ariza',
        nationality: 'Colombia',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/303942/History/Ronaldo-Ariza' },
    { name: 'Ronaldo Cordoba',
        nationality: 'Panama',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/303989/History/Ronaldo-Cordoba' },
    { name: 'Ronaldo Villa',
        nationality: 'Ecuador',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/311020/History/Ronaldo-Villa' },
    { name: 'Ronaldo Lucena',
        nationality: 'Venezuela',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/316982/History/Ronaldo-Lucena' },
    { name: 'Ronaldo Vieira',
        nationality: 'Brazil',
        club: 'Sampdoria',
        URL:
            'https://www.whoscored.com/Players/317179/History/Ronaldo-Vieira' },
    { name: 'Ronaldo Conceição',
        nationality: 'Brazil',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/319366/History/Ronaldo-Conceição' },
    { name: 'Ronaldo Gomez',
        nationality: 'Paraguay',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/323401/History/Ronaldo-Gomez' },
    { name: 'Ronaldo Abarca',
        nationality: 'Chile',
        club: 'Cobresal',
        URL:
            'https://www.whoscored.com/Players/323589/History/Ronaldo-Abarca' },
    { name: 'Ronaldo Damus',
        nationality: 'Haiti',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/324958/History/Ronaldo-Damus' },
    { name: 'Ronaldo Deaconu',
        nationality: 'Romania',
        club: 'Sepsi OSK',
        URL:
            'https://www.whoscored.com/Players/325126/History/Ronaldo-Deaconu' },
    { name: 'Ronaldo Chacon',
        nationality: 'Venezuela',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/329419/History/Ronaldo-Chacon' },
    { name: 'Ronaldo Tiismaa',
        nationality: 'Estonia',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/335721/History/Ronaldo-Tiismaa' },
    { name: 'Ronaldo Mesidu',
        nationality: 'Indonesia',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/337313/History/Ronaldo-Mesidu' },
    { name: 'Ronaldo Viera',
        nationality: 'United States',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/337781/History/Ronaldo-Viera' },
    { name: 'Ronaldo Wilkins',
        nationality: 'Vanuatu',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/338187/History/Ronaldo-Wilkins' },
    { name: 'Ronaldo Onate',
        nationality: 'Ecuador',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/340102/History/Ronaldo-Onate' },
    { name: 'Ronaldo Peña',
        nationality: 'Venezuela',
        club: 'Houston Dynamo',
        URL:
            'https://www.whoscored.com/Players/342612/History/Ronaldo-Peña' },
    { name: 'Ronaldo Lima',
        nationality: 'Netherlands',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/344038/History/Ronaldo-Lima' },
    { name: 'Ronaldo Vasquez',
        nationality: 'Dominican Republic',
        club: 'CA Pantoja',
        URL:
            'https://www.whoscored.com/Players/348418/History/Ronaldo-Vasquez' },
    { name: 'Ronaldo Andia',
        nationality: 'Peru',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/348577/History/Ronaldo-Andia' },
    { name: 'Ronaldo Wilkins',
        nationality: 'Vanuatu',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/349114/History/Ronaldo-Wilkins' },
    { name: 'Ronaldo Tavares',
        nationality: 'Portugal',
        club: 'Penafiel',
        URL:
            'https://www.whoscored.com/Players/354205/History/Ronaldo-Tavares' },
    { name: 'Ronaldo Wanma',
        nationality: 'Indonesia',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/354903/History/Ronaldo-Wanma' },
    { name: 'Ronaldo Baez',
        nationality: 'Paraguay',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/355213/History/Ronaldo-Baez' },
    { name: 'Ronaldo Tavera',
        nationality: 'Colombia',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/355416/History/Ronaldo-Tavera' },
    { name: 'Ronaldo Monteiro',
        nationality: 'Bolivia',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/360167/History/Ronaldo-Monteiro' },
    { name: 'Ronaldo Prieto',
        nationality: 'Mexico',
        club: 'Veracruz',
        URL:
            'https://www.whoscored.com/Players/360178/History/Ronaldo-Prieto' },
    { name: 'Ronaldo Dinolis',
        nationality: 'Panama',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/360828/History/Ronaldo-Dinolis' },
    { name: 'Ronaldo Moreno',
        nationality: 'Venezuela',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/366949/History/Ronaldo-Moreno' },
    { name: 'Shani Ronaldo',
        nationality: 'Greece',
        club: 'Atromitos',
        URL:
            'https://www.whoscored.com/Players/368710/History/Shani-Ronaldo' },
    { name: 'Ronaldo Araya',
        nationality: 'Costa Rica',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/369527/History/Ronaldo-Araya' },
    { name: 'Ronaldo Lora',
        nationality: 'Colombia',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/372704/History/Ronaldo-Lora' },
    { name: 'Ronaldo Filho',
        nationality: 'Brazil',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/373297/History/Ronaldo-Filho' },
    { name: 'Ronaldo Rivas',
        nationality: 'Venezuela',
        club: 'Estudiantes Merida',
        URL:
            'https://www.whoscored.com/Players/374362/History/Ronaldo-Rivas' },
    { name: 'Ronaldo Huari',
        nationality: 'Peru',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/374740/History/Ronaldo-Huari' },
    { name: 'Ronaldo Maarman',
        nationality: 'South Africa',
        club: 'Chippa United',
        URL:
            'https://www.whoscored.com/Players/381254/History/Ronaldo-Maarman' },
    { name: 'Ronaldo Baez',
        nationality: 'Paraguay',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/382201/History/Ronaldo-Baez' },
    { name: 'Simoes Ronaldo Angelim',
        nationality: 'Brazil',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/17468/History/Simoes-Ronaldo-Angelim' },
    { name: 'Ronaldo Da Silva',
        nationality: 'Brazil',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/61972/History/Ronaldo-Da-Silva' },
    { name: 'Vendry Ronaldo Mofu',
        nationality: 'Indonesia',
        club: 'N/A',
        URL:
            'https://www.whoscored.com/Players/319531/History/Vendry-Ronaldo-Mofu' },
    { name: 'Ronaldo Pah Paul',
        nationality: 'Norway',
        club: 'Byaasen',
        URL:
            'https://www.whoscored.com/Players/336896/History/Ronaldo-Pah-Paul' } ];

const stats = { '2019/2020 - ISA|Juventus':
        { minutes: 540,
            goals: 2,
            shots: 35,
            succPasses: 184,
            totalPasses: 221,
            succLongPasses: 3,
            totalLongPasses: 6,
            assists: 1,
            keyPasses: 9,
            throughBalls: 0,
            tackles: 2,
            dribbledPast: 3,
            interceptions: 1,
            possessionLosses: 6,
            dribbles: 11,
            clearances: 6,
            totalAerialDuels: 13,
            succAerialDuels: 8,
            succCrosses: 0,
            totalCrosses: 3,
            fouls: 1 },
    '2019/2020 - UCL|Juventus':
        { minutes: 180,
            goals: 1,
            shots: 8,
            succPasses: 71,
            totalPasses: 82,
            succLongPasses: 0,
            totalLongPasses: 0,
            assists: 0,
            keyPasses: 1,
            throughBalls: 0,
            tackles: 0,
            dribbledPast: 0,
            interceptions: 0,
            possessionLosses: 2,
            dribbles: 6,
            clearances: 1,
            totalAerialDuels: 6,
            succAerialDuels: 4,
            succCrosses: 0,
            totalCrosses: 5,
            fouls: 2 },
    '2018/2019 - ISA|Juventus':
        { minutes: 2689,
            goals: 16,
            shots: 171,
            succPasses: 877,
            totalPasses: 1031,
            succLongPasses: 30,
            totalLongPasses: 41,
            assists: 8,
            keyPasses: 48,
            throughBalls: 0,
            tackles: 10,
            dribbledPast: 10,
            interceptions: 6,
            possessionLosses: 39,
            dribbles: 45,
            clearances: 30,
            totalAerialDuels: 75,
            succAerialDuels: 33,
            succCrosses: 17,
            totalCrosses: 58,
            fouls: 19 },
    '2018/2019 - UCL|Juventus':
        { minutes: 749,
            goals: 5,
            shots: 47,
            succPasses: 225,
            totalPasses: 266,
            succLongPasses: 3,
            totalLongPasses: 5,
            assists: 2,
            keyPasses: 17,
            throughBalls: 0,
            tackles: 3,
            dribbledPast: 7,
            interceptions: 3,
            possessionLosses: 12,
            dribbles: 18,
            clearances: 6,
            totalAerialDuels: 34,
            succAerialDuels: 18,
            succCrosses: 2,
            totalCrosses: 19,
            fouls: 7 },
    '2018/2019 - UNL|Portugal':
        { minutes: 180,
            goals: 3,
            shots: 8,
            succPasses: 60,
            totalPasses: 71,
            succLongPasses: 2,
            totalLongPasses: 2,
            assists: 0,
            keyPasses: 3,
            throughBalls: 1,
            tackles: 0,
            dribbledPast: 0,
            interceptions: 0,
            possessionLosses: 6,
            dribbles: 5,
            clearances: 2,
            totalAerialDuels: 9,
            succAerialDuels: 2,
            succCrosses: 0,
            totalCrosses: 2,
            fouls: 1 },
    '2017/2018 - SLL|Real Madrid':
        { minutes: 2293,
            goals: 23,
            shots: 174,
            succPasses: 597,
            totalPasses: 732,
            succLongPasses: 13,
            totalLongPasses: 22,
            assists: 5,
            keyPasses: 38,
            throughBalls: 3,
            tackles: 7,
            dribbledPast: 5,
            interceptions: 6,
            possessionLosses: 27,
            dribbles: 31,
            clearances: 14,
            totalAerialDuels: 63,
            succAerialDuels: 34,
            succCrosses: 7,
            totalCrosses: 34,
            fouls: 19 },
    '2017/2018 - UCL|Real Madrid':
        { minutes: 1170,
            goals: 11,
            shots: 78,
            succPasses: 315,
            totalPasses: 387,
            succLongPasses: 5,
            totalLongPasses: 9,
            assists: 3,
            keyPasses: 15,
            throughBalls: 2,
            tackles: 5,
            dribbledPast: 3,
            interceptions: 3,
            possessionLosses: 10,
            dribbles: 22,
            clearances: 10,
            totalAerialDuels: 40,
            succAerialDuels: 22,
            succCrosses: 1,
            totalCrosses: 12,
            fouls: 6 },
    '2016/2017 - SLL|Real Madrid':
        { minutes: 2544,
            goals: 19,
            shots: 154,
            succPasses: 616,
            totalPasses: 770,
            succLongPasses: 11,
            totalLongPasses: 13,
            assists: 6,
            keyPasses: 31,
            throughBalls: 1,
            tackles: 6,
            dribbledPast: 7,
            interceptions: 8,
            possessionLosses: 39,
            dribbles: 25,
            clearances: 15,
            totalAerialDuels: 71,
            succAerialDuels: 35,
            succCrosses: 10,
            totalCrosses: 35,
            fouls: 18 },
    '2016/2017 - UCL|Real Madrid':
        { minutes: 1170,
            goals: 10,
            shots: 69,
            succPasses: 357,
            totalPasses: 411,
            succLongPasses: 4,
            totalLongPasses: 5,
            assists: 5,
            keyPasses: 20,
            throughBalls: 1,
            tackles: 3,
            dribbledPast: 7,
            interceptions: 4,
            possessionLosses: 30,
            dribbles: 15,
            clearances: 5,
            totalAerialDuels: 35,
            succAerialDuels: 19,
            succCrosses: 6,
            totalCrosses: 18,
            fouls: 9 },
    '2018 - WC|Portugal':
        { minutes: 360,
            goals: 3,
            shots: 19,
            succPasses: 95,
            totalPasses: 116,
            succLongPasses: 3,
            totalLongPasses: 4,
            assists: 0,
            keyPasses: 4,
            throughBalls: 1,
            tackles: 0,
            dribbledPast: 1,
            interceptions: 0,
            possessionLosses: 6,
            dribbles: 7,
            clearances: 4,
            totalAerialDuels: 15,
            succAerialDuels: 8,
            succCrosses: 0,
            totalCrosses: 2,
            fouls: 3 },
    '2015/2016 - SLL|Real Madrid':
        { minutes: 3185,
            goals: 29,
            shots: 218,
            succPasses: 850,
            totalPasses: 1070,
            succLongPasses: 12,
            totalLongPasses: 19,
            assists: 11,
            keyPasses: 51,
            throughBalls: 0,
            tackles: 11,
            dribbledPast: 12,
            interceptions: 8,
            possessionLosses: 44,
            dribbles: 51,
            clearances: 15,
            totalAerialDuels: 99,
            succAerialDuels: 56,
            succCrosses: 9,
            totalCrosses: 48,
            fouls: 22 },
    '2015/2016 - UCL|Real Madrid':
        { minutes: 1079,
            goals: 14,
            shots: 90,
            succPasses: 339,
            totalPasses: 407,
            succLongPasses: 5,
            totalLongPasses: 7,
            assists: 4,
            keyPasses: 23,
            throughBalls: 1,
            tackles: 3,
            dribbledPast: 1,
            interceptions: 3,
            possessionLosses: 20,
            dribbles: 7,
            clearances: 6,
            totalAerialDuels: 39,
            succAerialDuels: 15,
            succCrosses: 6,
            totalCrosses: 16,
            fouls: 12 },
    '2014/2015 - SLL|Real Madrid':
        { minutes: 3099,
            goals: 38,
            shots: 213,
            succPasses: 953,
            totalPasses: 1181,
            succLongPasses: 20,
            totalLongPasses: 28,
            assists: 16,
            keyPasses: 76,
            throughBalls: 5,
            tackles: 9,
            dribbledPast: 10,
            interceptions: 0,
            possessionLosses: 37,
            dribbles: 54,
            clearances: 27,
            totalAerialDuels: 108,
            succAerialDuels: 60,
            succCrosses: 22,
            totalCrosses: 81,
            fouls: 26 },
    '2014/2015 - UCL|Real Madrid':
        { minutes: 1065,
            goals: 7,
            shots: 67,
            succPasses: 349,
            totalPasses: 428,
            succLongPasses: 5,
            totalLongPasses: 8,
            assists: 3,
            keyPasses: 16,
            throughBalls: 0,
            tackles: 2,
            dribbledPast: 6,
            interceptions: 2,
            possessionLosses: 16,
            dribbles: 25,
            clearances: 11,
            totalAerialDuels: 36,
            succAerialDuels: 15,
            succCrosses: 4,
            totalCrosses: 20,
            fouls: 9 },
    '2016 - UEC|Portugal':
        { minutes: 565,
            goals: 3,
            shots: 43,
            succPasses: 159,
            totalPasses: 186,
            succLongPasses: 0,
            totalLongPasses: 0,
            assists: 2,
            keyPasses: 10,
            throughBalls: 1,
            tackles: 1,
            dribbledPast: 1,
            interceptions: 0,
            possessionLosses: 12,
            dribbles: 3,
            clearances: 6,
            totalAerialDuels: 35,
            succAerialDuels: 13,
            succCrosses: 1,
            totalCrosses: 1,
            fouls: 6 },
    '2013/2014 - SLL|Real Madrid':
        { minutes: 2545,
            goals: 25,
            shots: 210,
            succPasses: 767,
            totalPasses: 956,
            succLongPasses: 25,
            totalLongPasses: 28,
            assists: 9,
            keyPasses: 48,
            throughBalls: 1,
            tackles: 18,
            dribbledPast: 6,
            interceptions: 4,
            possessionLosses: 43,
            dribbles: 67,
            clearances: 14,
            totalAerialDuels: 101,
            succAerialDuels: 53,
            succCrosses: 10,
            totalCrosses: 49,
            fouls: 20 },
    '2013/2014 - UCL|Real Madrid':
        { minutes: 963,
            goals: 15,
            shots: 71,
            succPasses: 324,
            totalPasses: 385,
            succLongPasses: 10,
            totalLongPasses: 15,
            assists: 3,
            keyPasses: 21,
            throughBalls: 2,
            tackles: 5,
            dribbledPast: 2,
            interceptions: 1,
            possessionLosses: 14,
            dribbles: 25,
            clearances: 8,
            totalAerialDuels: 41,
            succAerialDuels: 18,
            succCrosses: 1,
            totalCrosses: 10,
            fouls: 8 },
    '2014 - WC|Portugal':
        { minutes: 270,
            goals: 1,
            shots: 22,
            succPasses: 74,
            totalPasses: 94,
            succLongPasses: 5,
            totalLongPasses: 6,
            assists: 1,
            keyPasses: 3,
            throughBalls: 0,
            tackles: 2,
            dribbledPast: 0,
            interceptions: 3,
            possessionLosses: 4,
            dribbles: 4,
            clearances: 1,
            totalAerialDuels: 6,
            succAerialDuels: 2,
            succCrosses: 1,
            totalCrosses: 5,
            fouls: 3 },
    '2012/2013 - SLL|Real Madrid':
        { minutes: 2721,
            goals: 28,
            shots: 228,
            succPasses: 831,
            totalPasses: 1083,
            succLongPasses: 20,
            totalLongPasses: 37,
            assists: 10,
            keyPasses: 63,
            throughBalls: 7,
            tackles: 14,
            dribbledPast: 2,
            interceptions: 10,
            possessionLosses: 50,
            dribbles: 56,
            clearances: 23,
            totalAerialDuels: 99,
            succAerialDuels: 56,
            succCrosses: 11,
            totalCrosses: 74,
            fouls: 27 },
    '2012/2013 - UCL|Real Madrid':
        { minutes: 1080,
            goals: 12,
            shots: 81,
            succPasses: 372,
            totalPasses: 470,
            succLongPasses: 10,
            totalLongPasses: 15,
            assists: 1,
            keyPasses: 23,
            throughBalls: 1,
            tackles: 5,
            dribbledPast: 5,
            interceptions: 6,
            possessionLosses: 28,
            dribbles: 25,
            clearances: 8,
            totalAerialDuels: 34,
            succAerialDuels: 18,
            succCrosses: 3,
            totalCrosses: 21,
            fouls: 7 },
    '2012 - UEC|Portugal':
        { minutes: 450,
            goals: 3,
            shots: 37,
            succPasses: 107,
            totalPasses: 131,
            succLongPasses: 1,
            totalLongPasses: 1,
            assists: 0,
            keyPasses: 10,
            throughBalls: 1,
            tackles: 2,
            dribbledPast: 1,
            interceptions: 1,
            possessionLosses: 7,
            dribbles: 5,
            clearances: 2,
            totalAerialDuels: 8,
            succAerialDuels: 4,
            succCrosses: 1,
            totalCrosses: 11,
            fouls: 4 },
    '2011/2012 - SLL|Real Madrid':
        { minutes: 3354,
            goals: 34,
            shots: 251,
            succPasses: 1132,
            totalPasses: 1405,
            succLongPasses: 40,
            totalLongPasses: 51,
            assists: 12,
            keyPasses: 60,
            throughBalls: 12,
            tackles: 19,
            dribbledPast: 9,
            interceptions: 19,
            possessionLosses: 79,
            dribbles: 73,
            clearances: 25,
            totalAerialDuels: 57,
            succAerialDuels: 30,
            succCrosses: 22,
            totalCrosses: 86,
            fouls: 32 },
    '2011/2012 - UCL|Real Madrid':
        { minutes: 900,
            goals: 8,
            shots: 70,
            succPasses: 322,
            totalPasses: 409,
            succLongPasses: 7,
            totalLongPasses: 14,
            assists: 3,
            keyPasses: 24,
            throughBalls: 1,
            tackles: 8,
            dribbledPast: 1,
            interceptions: 7,
            possessionLosses: 18,
            dribbles: 28,
            clearances: 2,
            totalAerialDuels: 23,
            succAerialDuels: 10,
            succCrosses: 3,
            totalCrosses: 28,
            fouls: 4 },
    '2010/2011 - SLL|Real Madrid':
        { minutes: 2913,
            goals: 32,
            shots: 242,
            succPasses: 948,
            totalPasses: 1253,
            succLongPasses: 23,
            totalLongPasses: 34,
            assists: 11,
            keyPasses: 67,
            throughBalls: 11,
            tackles: 17,
            dribbledPast: 5,
            interceptions: 24,
            possessionLosses: 76,
            dribbles: 75,
            clearances: 24,
            totalAerialDuels: 74,
            succAerialDuels: 49,
            succCrosses: 9,
            totalCrosses: 91,
            fouls: 24 },
    '2010/2011 - UCL|Real Madrid':
        { minutes: 1021,
            goals: 5,
            shots: 72,
            succPasses: 414,
            totalPasses: 490,
            succLongPasses: 6,
            totalLongPasses: 6,
            assists: 4,
            keyPasses: 21,
            throughBalls: 2,
            tackles: 5,
            dribbledPast: 2,
            interceptions: 8,
            possessionLosses: 27,
            dribbles: 32,
            clearances: 7,
            totalAerialDuels: 30,
            succAerialDuels: 19,
            succCrosses: 1,
            totalCrosses: 24,
            fouls: 13 },
    '2009/2010 - SLL|Real Madrid':
        { minutes: 2490,
            goals: 22,
            shots: 206,
            succPasses: 892,
            totalPasses: 1119,
            succLongPasses: 15,
            totalLongPasses: 24,
            assists: 7,
            keyPasses: 75,
            throughBalls: 2,
            tackles: 13,
            dribbledPast: 4,
            interceptions: 13,
            possessionLosses: 80,
            dribbles: 91,
            clearances: 4,
            totalAerialDuels: 54,
            succAerialDuels: 26,
            succCrosses: 17,
            totalCrosses: 108,
            fouls: 39 },
    '2009/2010 - UCL|Real Madrid':
        { minutes: 450,
            goals: 7,
            shots: 32,
            succPasses: 176,
            totalPasses: 216,
            succLongPasses: 5,
            totalLongPasses: 7,
            assists: 0,
            keyPasses: 9,
            throughBalls: 0,
            tackles: 3,
            dribbledPast: 2,
            interceptions: 4,
            possessionLosses: 15,
            dribbles: 14,
            clearances: 4,
            totalAerialDuels: 14,
            succAerialDuels: 11,
            succCrosses: 1,
            totalCrosses: 13,
            fouls: 3 } }


module.exports = {
    searchResults, stats
};